# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9ea324de89d141a2d32ac456866111dc85bf75e1cf1ee47d5efb5943651a046547fe4fd9657073506ddc5ec727d33fb2e3c60cbad296ba6d295dd6a7085908

test:
  secret_key_base: 2194d4bc7369831e09fb7dda78120022b67e1a45100ba6c2f5f826405abfea78c15493e8e983d03381c5c6529869f8365ed2957c43d0483786f5e03846b4b925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
